### ISSUE TITLE
ClassInvocationStub.java line 110 top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke

### ISSUE THREAD

**Issue by bascobasco** [FBlackBox/BlackBox#63]
**Describe the bug** / **描述一下这个错误**
清晰而简明地描述什么是错误。
This bug was reported by firebase which we use to collect crashes and it shows that it affects 9 users at the moment with 166 crash events.
**To Reproduce** / **复现步骤**

**Expected behavior** / **预期的行为**
清晰而简明地描述你所期望发生的事情。

**Screenshots** / **截图**
如果有，请添加屏幕截图以帮助解释你的问题。

**Mobile Phone Info** / **手机信息**
Xiaomi / Android12
1.Samsung Galaxy M11 (android 11)
2. Galaxy Tab A7 Lite (android 11)
3.Galaxy A21s (android 11)
4. realme C25s (Android 11)
5. xiomi  Redmi 9(android 11)
6. Redmi Note 10 Pro (Android 11)

**Logcat** / **日志**
If you are a developer or capable please provide logs for us to analyze.
如果你是开发者或者有能力的请提供日志供我们分析。
Fatal Exception: java.lang.SecurityException: MATCH_ANY_USER flag requires INTERACT_ACROSS_USERS permission at com.android.server.pm.PackageManagerService.getSharedLibraries:6616 android.content.pm.IPackageManager$Stub.onTransact:4495 com.android.server.pm.PackageManagerService.onTransact:5360 android.os.Binder.execTransactInternal:1190 android.os.Binder.execTransact:1159 : Requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at android.content.pm.IPackageManager$Stub$Proxy.getSharedLibraries(IPackageManager.java:9425)
       at java.lang.reflect.Method.invoke(Method.java)
       at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:110)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at $Proxy15.getSharedLibraries()
       at android.app.ApplicationPackageManager.getSharedLibrariesAsUser(ApplicationPackageManager.java:639)
       at android.app.ApplicationPackageManager.getSharedLibraries(ApplicationPackageManager.java:631)
       at pxr.u(PG:1)
       at pxr.t(:1)
       at omq.g(PG:32)
       at fai.run(PG:11)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at iih.run(PG:16)
       at java.lang.Thread.run(Thread.java:923)

**Additional context** / **额外内容**
在此添加关于该问题的任何其他内容。

**APK**
If applicable, add the apk file for me to test.
如果有，请添加APK文件给我测试。

**Comment by FBlackBox** [comment]
Fixed, please update BCore

**Comment by bascobasco** [comment]
@FBlackBox this error keeps on happening even after updating.Our users are still experiencing the issue.
The  logs are:

`Fatal Exception: java.lang.SecurityException: Shortcut package name mismatch
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at android.content.pm.IShortcutService$Stub$Proxy.pushDynamicShortcut(IShortcutService.java:1390)
       at java.lang.reflect.Method.invoke(Method.java)
       at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:110)
       at top.niunaijun.blackbox.fake.service.IShortcutManagerProxy.invoke(IShortcutManagerProxy.java:80)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at $Proxy41.pushDynamicShortcut()
       at android.content.pm.ShortcutManager.pushDynamicShortcut(ShortcutManager.java:792)
       at X.0Rq.A0F(:125584)
       at X.0Rq.A0E(:125572)
       at X.04C.A03(:20895)
       at X.3Ea.A03(:536063)
       at X.3Ea.run(:536494)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by FBlackBox** [comment]
Fixed,Please submit a new issue next time.
